"""Export a finished comparison run to web/src/data/comparison.json.

The Overview screen needs numbers the moment someone opens it. A deployed
instance starts with an empty database (ephemeral disk), and computing 3,000
cases takes minutes -- so a first visitor would otherwise land on an empty
page and be asked to wait. This bakes the results of a real run into the
frontend bundle as the starting view.

What it writes is the actual output of the simulator, read back out of the
database -- never hand-entered figures. The run is seeded, so pressing "Run
both policies" reproduces exactly these numbers.

Usage:
    python -m scripts.export_comparison            # seed 42, 3000 cases
    python -m scripts.export_comparison 42 3000

Run the comparison first if the database does not have it yet:
    curl -X POST localhost:8000/api/runs \\
         -H 'Content-Type: application/json' \\
         -d '{"policy":"both","count":3000,"seed":42}'
"""

import datetime
import json
import pathlib
import sys

from sqlalchemy import select

from app import simulator
from app.db import SessionLocal
from app.models import RunMetric

OUT = pathlib.Path(__file__).resolve().parents[1] / "web" / "src" / "data" / "comparison.json"

COMMENT = (
    "Generated by scripts/export_comparison.py from a real run -- these are the "
    "simulator's own numbers read back out of the database, not hand-written "
    "figures. Committed so the Overview screen has something to show on a cold "
    "deployment, where the database starts empty. The run is seeded, so "
    "reproducing it from the Compare screen yields exactly these figures."
)


def export(seed: int = 42, count: int = 3000) -> pathlib.Path:
    session = SessionLocal()
    try:
        policies, causes = {}, {}
        for policy in ("baseline", "router"):
            run_id = f"{policy}-s{seed}-n{count}"
            if session.scalar(select(RunMetric).where(RunMetric.run_id == run_id)) is None:
                raise SystemExit(
                    f"no stored run '{run_id}'. Run the comparison first -- see this file's docstring."
                )
            policies[policy] = {**simulator.compute_metrics(session, run_id), "policy": policy}
            causes[policy] = _by_cause(session, run_id)

        payload = {
            "_comment": COMMENT,
            "seed": seed,
            "count": count,
            "generated_at": datetime.date.today().isoformat(),
            "policies": policies,
            "causes": causes,
        }
    finally:
        session.close()

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return OUT


def _by_cause(session, run_id: str) -> list[dict]:
    """Same shape the /api/runs/{id}/by-cause endpoint returns."""
    from app.routes.runs import by_cause

    return by_cause(run_id, session)["causes"]


if __name__ == "__main__":
    seed = int(sys.argv[1]) if len(sys.argv) > 1 else 42
    count = int(sys.argv[2]) if len(sys.argv) > 2 else 3000
    path = export(seed, count)
    data = json.loads(path.read_text(encoding="utf-8"))
    print(f"wrote {path}")
    for name, metrics in data["policies"].items():
        print(
            f"  {name:<9} {metrics['messages_sent']:>5} messages  "
            f"{metrics['wrong_advice_count']:>4} wrong advice  "
            f"{metrics['recovery_rate'] * 100:.1f}% recovered"
        )
